# Generated by Django 4.2.20 on 2025-04-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('email', models.EmailField(max_length=254)),
                ('gst_no', models.CharField(max_length=50)),
                ('is_special_seller', models.BooleanField(default=False)),
            ],
        ),
    ]
