# Generated by Django 4.2.20 on 2025-05-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bookmark',
            field=models.TextField(default='[]'),
        ),
    ]
